require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*

Documentation:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/LineLength:
  Max: 100
  Exclude:
    - config/environments/*
    - config/initializers/*
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Layout/SpaceBeforeFirstArg:
  Exclude:
    - app/views/api/**/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 15


Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 24

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/SaveBang:
  Enabled: true

Style/BlockComments:
  Exclude:
  - spec/spec_helper.rb

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ReturnNil:
  Enabled: true
