aleen = User.find_or_create_by!(name: 'Aleen', email: 'aleen@example.com')
gilbert = User.find_or_create_by!(name: 'Gilbert', email: 'gilbert@example.com')
jhon = User.find_or_create_by!(name: 'Jhon', email: 'jhon@example.com')
kerry = User.find_or_create_by!(name: 'Kerry', email: 'kerry@example.com')
livia = User.find_or_create_by!(name: 'Livia', email: 'livia@example.com')
mellisa = User.find_or_create_by!(name: 'Mellisa', email: 'mellisa@example.com')
ozzie = User.find_or_create_by!(name: 'Ozzie', email: 'ozzie@example.com')
richard = User.find_or_create_by!(name: 'Richard', email: 'richard@example.com')
suzann = User.find_or_create_by!(name: 'Suzann', email: 'suzann@example.com')
willy = User.find_or_create_by!(name: 'Willy', email: 'willy@example.com')

Friendship.find_or_create_by!(user: aleen, friend: livia)
Friendship.find_or_create_by!(user: aleen, friend: kerry)
Friendship.find_or_create_by!(user: livia, friend: suzann)
Friendship.find_or_create_by!(user: livia, friend: gilbert)
Friendship.find_or_create_by!(user: kerry, friend: suzann)
Friendship.find_or_create_by!(user: kerry, friend: suzann)
Friendship.find_or_create_by!(user: gilbert, friend: jhon)
Friendship.find_or_create_by!(user: jhon, friend: mellisa)
Friendship.find_or_create_by!(user: willy, friend: richard)

payment_6 = Payment.find_or_create_by!(sender: mellisa, receiver: jhon, amount: 100, created_at: 5.days.ago, description: "This is a #{mellisa.name}‘s payment")
payment_5 = Payment.find_or_create_by!(sender: gilbert, receiver: jhon, amount: 100, created_at: 4.days.ago, description: "This is a #{gilbert.name}‘s payment")
payment_4 = Payment.find_or_create_by!(sender: gilbert, receiver: jhon, amount: 100, created_at: 3.days.ago, description: "This is a #{gilbert.name}‘s payment 2")
payment_3 = Payment.find_or_create_by!(sender: kerry, receiver: suzann, amount: 50, created_at: 2.days.ago, description: "This is a #{kerry.name}‘s payment")
payment_2 = Payment.find_or_create_by!(sender: livia, receiver: gilbert, amount: 40, created_at: 1.day.ago, description: "This is a #{livia.name}‘s payment")
payment_1 = Payment.find_or_create_by!(sender: aleen, receiver: livia, amount: 100, created_at: Time.zone.today, description: "This is a #{aleen.name}‘s payment")

Event.find_or_create_by!(user: mellisa, created_at: 5.days.ago, content: "#{payment_6.sender.name} paid #{payment_6.receiver.name} on #{payment_6.created_at.strftime('%d %b %H:%M')} - #{payment_6.description}")
Event.find_or_create_by!(user: gilbert, created_at: 4.days.ago, content: "#{payment_5.sender.name} paid #{payment_5.receiver.name} on #{payment_5.created_at.strftime('%d %b %H:%M')} - #{payment_5.description}")
Event.find_or_create_by!(user: gilbert, created_at: 3.days.ago, content: "#{payment_4.sender.name} paid #{payment_4.receiver.name} on #{payment_4.created_at.strftime('%d %b %H:%M')} - #{payment_4.description}")
Event.find_or_create_by!(user: kerry, created_at: 2.days.ago, content: "#{payment_3.sender.name} paid #{payment_3.receiver.name} on #{payment_3.created_at.strftime('%d %b %H:%M')} - #{payment_3.description}")
Event.find_or_create_by!(user: livia, created_at: 1.day.ago, content: "#{payment_2.sender.name} paid #{payment_2.receiver.name} on #{payment_2.created_at.strftime('%d %b %H:%M')} - #{payment_2.description}")
Event.find_or_create_by!(user: aleen, created_at: Time.zone.today, content: "#{payment_1.sender.name} paid #{payment_1.receiver.name} on #{payment_1.created_at.strftime('%d %b %H:%M')} - #{payment_1.description}")

aleen.account.update!(balance: 900)
gilbert.account.update!(balance: 1_160)
jhon.account.update!(balance: 1_300)
kerry.account.update!(balance: 950)
livia.account.update!(balance: 1_060)
mellisa.account.update!(balance: 900)
ozzie.account.update!(balance: 1_000)
richard.account.update!(balance: 1_000)
suzann.account.update!(balance: 1_050)
willy.account.update!(balance: 1_000)
